services:
  pocketbase:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bibletype-pocketbase
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data  # Main database storage
      - ./pb_migrations:/pb/pb_migrations  # Migration files
      - ./pb_hooks:/pb/pb_hooks  # JavaScript hooks
    networks:
      - cf_tunnel

networks:
  cf_tunnel:
    external: true
